apiVersion: cdr.hsdp.crossplane.io/v1alpha1
kind: Subscription
metadata:
  name: patient-subscription
  namespace: crossplane-system
spec:
  forProvider:
    name: patient-subscription
    fhirStore: "https://cdr-stu3-sandbox.hsdp.io/store/fhir/root-iam-org-uuid"
    version: "r4"
    criteria:  "Patient"
    reason: "Notification for patient changes"
    endpoint: "https://webhook.myapp.io/patient"
    deleteEndpoint: "https://webhook.myapp.io/patient_deleted"
    headers:
      - "Authorization: Basic cm9uOnN3YW5zb24="
    end: "2030-12-31T23:59:59Z"

